version: '3.9'

networks:
  k6:
  grafana:

services:

  # k6:
  #   image: loadimpact/k6
  #   container_name: k6
  #   networks:
  #     - k6
  #   environment:
  #     - K6_OUT=influxdb=http://influxdb:8086/k6
  #   volumes:
  #     - ./scripts:/scripts
  
  influxdb:
    image: influxdb:1.8.10
    container_name: influxdb
    networks:
      - k6
      - grafana
    environment:
      - INFLUXDB_DB=k6
      - INFLUXDB_HTTP_MAX_BODY_SIZE=0
    ports:
      - 8086:8086
    volumes:
      - ./data/influxdb:/var/lib/influxdb

  grafana:
    image: grafana/grafana
    container_name: grafana
    networks:
      - grafana
    environment:
      # - GF_AUTH_ANONYMOUS_ENABLED=false
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_SERVER_HTTP_PORT=3300
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=test
    ports:
      - 3300:3300
    volumes:
      - ./data/grafana:/var/lib/grafana

  jenkins:
    image: jenkins/jenkins:lts-jdk11
    privileged: true
    user: root
    container_name: jenkins
    networks:
      - k6
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - ./jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
